// templates/sveltekit-supabase/src/routes/dashboard/+page.svelte
<script lang="ts">
  import { enhance } from '$app/forms';
  export let data;
  export let form;
</script>

<svelte:head>
  <title>Dashboard &middot; {{PROJECT_NAME}}</title>
</svelte:head>

<main class="container">
  <h1>Dashboard</h1>
  <div class="card">
    <p>Signed in as <strong>{data.user?.email}</strong>.</p>
    <p>This protected route is only reachable with a valid session.</p>
    <form method="POST" action="?/signout" use:enhance>
      <button type="submit">Sign out</button>
    </form>
  </div>
</main>

// templates/nextjs-supabase/app/dashboard/page.tsx
import { createClient } from "@/lib/supabase/server";
import { redirect } from "next/navigation";
import { signOut } from "./actions";

export default async function Dashboard() {
  const supabase = createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();

  // Protected route: bounce unauthenticated (or unconfirmed) users.
  if (!user) {
    redirect("/login");
  }

  return (
    <main className="container">
      <div className="card">
        <h2>Dashboard</h2>
        <p>
          Signed in as <strong>{user.email}</strong>
        </p>
        <p className="nav">User ID: {user.id}</p>
        <form action={signOut}>
          <button type="submit" className="secondary">
            Sign out
          </button>
        </form>
      </div>
    </main>
  );
}
