// templates/sveltekit-supabase/src/routes/login/+page.svelte
<script lang="ts">
  import { enhance } from '$app/forms';
  export let form;
</script>

<svelte:head>
  <title>Log in &middot; {{PROJECT_NAME}}</title>
</svelte:head>

<main class="container">
  <h1>Log in</h1>

  <div class="card">
    <form method="POST" use:enhance>
      <label for="email">Email</label>
      <input id="email" name="email" type="email" value={form?.email ?? ''} required />

      <label for="password">Password</label>
      <input id="password" name="password" type="password" required />

      <button type="submit">Log in</button>
    </form>

    {#if form?.error}
      <p class="error">{form.error}</p>
    {/if}

    <p style="margin-top:1rem">No account? <a href="/signup">Sign up</a></p>
  </div>
</main>

// templates/nextjs-supabase/app/login/page.tsx
"use client";

import { useFormState, useFormStatus } from "react-dom";
import { signIn } from "./actions";

function SubmitButton() {
  const { pending } = useFormStatus();
  return (
    <button type="submit" disabled={pending}>
      {pending ? "Signing in…" : "Sign in"}
    </button>
  );
}

export default function LoginPage({
  searchParams,
}: {
  searchParams: { error?: string };
}) {
  const [state, formAction] = useFormState(signIn, { error: null as string | null });

  return (
    <main className="container">
      <div className="card">
        <h2>Sign in</h2>
        {searchParams.error && <p className="error">{searchParams.error}</p>}
        {state.error && <p className="error">{state.error}</p>}
        <form action={formAction}>
          <label htmlFor="email">Email</label>
          <input id="email" name="email" type="email" required autoComplete="email" />
          <label htmlFor="password">Password</label>
          <input
            id="password"
            name="password"
            type="password"
            required
            autoComplete="current-password"
          />
          <SubmitButton />
        </form>
        <p className="nav">
          No account? <a href="/signup">Sign up</a>
        </p>
      </div>
    </main>
  );
}
